### ISSUE TITLE
Entity/GUI interaction

### ISSUE THREAD

**Issue by Cnorine1** [maximusg/GameShazy#6]
Finalize Entity/GUI interaction

**Comment by Cnorine1** [comment]
i'd like to revisit the idea of polling the keyboard inside of the entity group of classes. I don't think it makes sense from a "what are the jobs of things" perspective. The GUI should tell the ship what buttons were pressed, at a minimum, then the ship executes the appropriate action based on what is passed.

Thoughts?

**Comment by Cnorine1** [comment]
Proposal. 

Move pygame.key.get_pressed() back into the GUI, and pass the resulting list to playerShip.control(). We get the same result without entity reaching into IO

plus the added bonus that we can still use the array for any processing further down processing for the given frame.

**Comment by maximusg** [comment]
Yes! Totally agree

**Comment by maximusg** [comment]
I didn't think of that. Def makes sense.

**Comment by maximusg** [comment]
This seems to be fixed
